### ISSUE TITLE
schema does now allow service values

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#1006]
If a service has values defined, it fails validation:
```yaml
        - name: kube-lego
          registry: quay.io
          chart: samsung_cnct/kube-lego
          version: '0.0.5-0'
          namespace: ingress
          values:
            image: "jetstack/kube-lego:0.1.4"
            email: letsencrypt@domain.dom
            domain: launchdock.io
            api: "https://acme-v01.api.letsencrypt.org/directory"
```
