### ISSUE TITLE
authn.oidc is not allowed by schema

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#1007]
In order to use dex auth, oidc needs to be able to be configured:

```yaml
      authn:
        oidc:
          service_name: dex
          issuer: "https://auth.domain.dom"
          domain: auth.domain.dom
```
