### ISSUE TITLE
BAC-107 ⁃ Move kube-proxy from static pod to daemonset

### ISSUE THREAD

**Issue by venezia** [samsung-cnct/kraken-lib#1045]
Right now kube-proxy is running as static pods on nodes, let's move it to a daemonset

## Advantages:
 - remote management (ability to restart/upgrade kube-proxy without adjusting cloud-config/rebooting node) - including the ability to add/remove verbosity of kube proxy logs

## Disadvantages:
 - Generally speaking kube-proxy as a manifest is working, so why change it?

### Currently an inconsistent connection to API Server

Currently, `kube-proxy` connects to apiserver on an insecure port on master nodes, uses `kubelet`'s `kubeconfig.yaml` on worker nodes.

We should have a consistent approach to connecting to the API Server, and it shouldn't have greater permissions than it needs to.  Let's create a kubeconfig.yaml that has a certificate that grants rights to kube-proxy.  This certificate should have `"/O=system:node-proxier/CN=system:kube-proxy"` in the openssl request command.

For example: 
```
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
openssl ecparam -genkey -name secp521r1 -out ${DIR}/../private/node-1-proxy.key
chmod og-wrx ${DIR}/../private/node-1-proxy.key
openssl req -new -key ${DIR}/../private/node-1-proxy.key -out ${DIR}/../csr/node-1-proxy.csr -subj "/O=system:node-proxier/CN=system:kube-proxy" -config ${DIR}/default.cnf
openssl x509 -req -in ${DIR}/../csr/node-1-proxy.csr \
-CA ${DIR}/../certs/ca.pem -CAkey ${DIR}/../private/ca.key -CAcreateserial \
-out ${DIR}/../certs/node-1-proxy.pem -days 3650 -extensions v3_req -extfile ${DIR}/default.cnf
```

## How could this be done
Similar to how we handle kube-dns, we should have a kraken service step that installs node-proxy as a daemonset.  Here is an example that we could use:

kube-proxy-kubeconfig.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    app: kube-proxy
data:
  kubeconfig.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: redacted
        server: https://apiserver.some-cluster.local
      name: some-cluster
    contexts:
    - context:
        cluster: some-cluster
        user: kube-proxy
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
    - name: kube-proxy
      user:
        as-user-extra: {}
        client-certificate-data: redacted
        client-key-data: redacted
```

kube-proxy-daemonset.yaml
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
    spec:
      containers:
      - name: kube-proxy
        image: k8s.gcr.io/kube-proxy-amd64:v1.9.0
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/kube-proxy
        - --kubeconfig=/var/lib/kube-proxy/kubeconfig.yaml
        - --proxy-mode=iptables
        - --logtostderr=true
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
          readOnly: false
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
      hostNetwork: true
      tolerations:
      volumes:
      - name: kube-proxy
        configMap:
          name: kube-proxy
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: lib-modules
        hostPath:
          path: /lib/modules
```

Tolerations may be needed to be added to ensure kube-proxy is also tageting the control plane nodes
