### ISSUE TITLE
Clean up helmOverride

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/kraken-lib#508]
As mentioned [here](https://github.com/samsung-cnct/k2/pull/497) the schema for helmOverride is not as useful as it could because the type of helmOveride may be a boolean ([22 different ways](http://yaml.org/type/bool.html)) when specified by the config file, a string when specified by an environment variable, or undefined when using an older configuration file.

I believe the root of this problem is that helmOverride has two distinct purposes:

 - Allow potentially incompatible versions of helm to be used anyway
 - Allow helm to be skipped entirely

The latter of these purposes has been requested by other customers, and I think the easiest way to accommodate this behavior is to allow the user to remove the helmConfig line from the cluster definition within the configuration file. For example:

```
deployment:
  clusters:
    - name: dewMaybe
...
      fabricConfig: *kubeVersionedFabric
      kubeAuth: *defaultKubeAuth
      #helmConfig: *defaultHelm
      dnsConfig: *defaultDns
...
```

Since the stanza is commented out, helm should be skipped...

For the former purpose, to proceed or not when there is no supported version of helm for the chosen kubernetes version, a boolean will suffice. If it is true, then use the latest version of helm available, even if it does not support the requested version of k8s. If it is false, then fail if the requested version of kubernetes does not have a supported version of helm. The failure message should indicate that the config file or an environment variable can be specified to proceed with an unsupported version of helm.

In this scheme, to support old versions of the configuration file, by default the helmOverride value should be false.
