### ISSUE TITLE
labels need to move up one level 

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken-lib#762]
according to https://github.com/samsung-cnct/k2/blob/master/Documentation/kraken-configs/node/aws-node.md, labels are currently being set under provider like this: 
```
  - &defaultAwsMasterNode
    name: defaultAwsMasterNode
    kind: node
    mounts:
      -
        device: sdf
        path: /var/lib/docker
        forceFormat: true
    providerConfig:
      provider: aws
      type: m3.medium
      subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
      label:
        - name: label
          value: this is an example
        - name: another_label
          value: one more example
```
they should be moved to be at the same level as `providerConfig`
