### ISSUE TITLE
Pin docker version explicitly in config file

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken-lib#946]
We get docker from coreos. We don't have control over which docker we get from coreos any given day. In order to ensure that our docker version conforms to tested standards, we need to pin an explicit version of docker via uri in the config file.

The current docker version used in Kubernetes e2e tests is 1.13.1. Our current coreOS uses 1.12.6 currently but the most recent coreOS release is moving to docker CE 17.09.0 on their alpha release.

The following stanza 
```
 containerConfigs:
    - &defaultDocker
      name: defaultDocker
      kind: container
      runtime: docker
      type: distro
```

should follow schema as per [here](https://github.com/samsung-cnct/kraken-lib/blob/master/schemas/config/v1/dockerContainerConfig.json#L25-L34) and add the correct information to match the `when` conditions in the [unit generation file](https://github.com/samsung-cnct/kraken-lib/blob/476683367d9552e31a2d7a02721d900ca7c08ee1/ansible/roles/kraken.cluster_common/tasks/units.yaml#L2-L110).
